### PR TITLE
Update getdeps.sh to avoid sudo on every run.

### PR DESCRIPTION
**Pull request by oridb**
```
In addition to wanting a password for no-ops, this allows
for easier scripting of automated building.
```

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
@oridb updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@oridb updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@oridb updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@oridb updated the pull request.

**Comment by capveg** [comment]
I believe this pull request is no longer needed.  Please confirm.

**Pull request closed without merging**
