### PR TITLE
tahan: config: adjusted sensor config to support 2nd source

### PR DESCRIPTION
**Pull request by zhongedward**
Description
This PR is for tahan 2nd source sensor service.

Motivation
1.Than 2nd source sensor list is as following:
https://docs.google.com/spreadsheets/d/1r0Vbv1cx3KelYLEM4vl0VNyIeEpFwurG5JJZ6BckMCI/edit?gid=1266933266#gid=1266933266
image

image

2.Currently,all the SMB number combinations and COME number combinations are as follows,in the future if factories have new numbers, we should add them.
image

3.In platform config, adjust SMBFRU_SLOT to SMB_FRU_SLOT,adjust BCB_SLOT.

4.Test Plan
1.The correctness of the format has been verified on this website https://jsonlint.com/ 
2.Used jq cmd to pretty the format.
3.Test log as follows:
Tested both in janga dvt main source & janga dvt 2nd source machine.

tahan 2nd source tested log:
image

tahan main source tested log:

tahan_dvt

[tahan_dvt_2nd_source_platform_test_log.txt](https://dev.azure.com/celestica-hps/89689cf2-cfd3-42fd-afd4-dd867f890ff0/_apis/git/repositories/4c32c16c-7172-448c-b01f-4d18aa18cd31/pullRequests/13786/attachments/tahan_dvt_2nd_source_platform_test_log.txt) [tahan_dvt_2nd_source_sensor_test_log.txt](https://dev.azure.com/celestica-hps/89689cf2-cfd3-42fd-afd4-dd867f890ff0/_apis/git/repositories/4c32c16c-7172-448c-b01f-4d18aa18cd31/pullRequests/13786/attachments/tahan_dvt_2nd_source_sensor_test_log.txt) [tahan_dvt_platform_test_log.txt](https://dev.azure.com/celestica-hps/89689cf2-cfd3-42fd-afd4-dd867f890ff0/_apis/git/repositories/4c32c16c-7172-448c-b01f-4d18aa18cd31/pullRequests/13786/attachments/tahan_dvt_platform_test_log.txt) [tahan_dvt_sensor_test_log.txt](https://dev.azure.com/celestica-hps/89689cf2-cfd3-42fd-afd4-dd867f890ff0/_apis/git/repositories/4c32c16c-7172-448c-b01f-4d18aa18cd31/pullRequests/13786/attachments/tahan_dvt_sensor_test_log.txt) 

FYI: the sensor_hw_test_log:
[tahan_dvt_2nd_source_sensor_hw_test_log.txt](https://github.com/user-attachments/files/17456086/tahan_dvt_2nd_source_sensor_hw_test_log.txt)
[tahan_dvt_sensor_hw_test_log.txt](https://github.com/user-attachments/files/17456087/tahan_dvt_sensor_hw_test_log.txt)

### CODE REVIEW

**Comment by zhongedward** [comment]
1.
[kimdo8736](https://github.com/kimdo8736) approved these changes [last week](https://github.com/facebook/fboss/pull/281#pullrequestreview-2434729154)

2.Because of conflicts, so i raised a same new one PR(i have abandoned the num 281), please help to merge thanks.

**Review by mikechoifb — APPROVED** [review]

**Comment by mikechoifb** [comment]
In the line 940 (not sure, please confirm)
"slotPath": "BCB_SLOT@0",

This needs to be changed to 
"slotPath": "/BCB_SLOT@0",

(That is, adding /)

Can you make this change, and update the PR, @zhongedward ?

**Review by mikechoifb — CHANGES_REQUESTED** [review]
Some of the meta internal test failing. Asked for further revision.

**Comment by zhongedward** [comment]
> In the line 940 (not sure, please confirm) "slotPath": "BCB_SLOT@0",
> 
> This needs to be changed to "slotPath": "/BCB_SLOT@0",
> 
> (That is, adding /)
> 
> Can you make this change, and update the PR, @zhongedward ?

@mikechoifb Ok, I have modified it, please review, thanks.
image

**Pull request closed without merging**
