### PR TITLE
Meru800bia: adds initial weutil config file

### PR DESCRIPTION
**Pull request by DeanKalla**
### Summary
Adds initial weutil config file for Meru800bia platform. This config file supports reading SCM EEPROM.

### Testing
**weutil --eeprom SCM --config_file weutil.json**

### CODE REVIEW

**Comment by joancaneus** [comment]
@DeanKalla we need to add the offset and idEepromFormatVer field for this PR just like the weutil json in this path https://github.com/facebook/fboss/blob/main/fboss/platform/configs/montblanc/weutil.json

Please make the change and send it again.

**Comment by DeanKalla** [comment]
> @DeanKalla we need to add the offset and idEepromFormatVer field for this PR just like the weutil json in this path https://github.com/facebook/fboss/blob/main/fboss/platform/configs/montblanc/weutil.json
> 
> Please make the change and send it again.

what is "offset" here? 
@arajeev-ARISTA

**Comment by arajeev-ARISTA** [comment]
Hi @DeanKalla, the offset is 15360

**Comment by DeanKalla** [comment]
I will discard this PR and arajeev will post a new one

**Comment by joancaneus** [comment]
> I will discard this PR and arajeev will post a new one

@DeanKalla  @arajeev-ARISTA --- by the way, I added the offset: 0 field and tested it and it works. However, that's with your weutil change which is not using offset at all and reading the whole buffetsize. I put a comment there as well for you to take a look tomorrow. 

Thanks Guys!

**Pull request closed without merging**
