### PR TITLE
janga800bic : added led_manager.json

### PR DESCRIPTION
**Pull request by GoravGargCelestica**
# Description

Added `led_manager.json` file to verify the `data_corral_service` and the `data_corral_service_hw_test`.

# Motivation

Aim is to verify the `data_corral_service` and the `data_corral_service_hw_test`.

# Testing 

1. `jq` command output is clean.

2. **Data Corral Service Logs :** [j3_data_corral_service_logs.txt](https://github.com/user-attachments/files/17038143/j3_data_corral_service_logs.txt)

3. **Data Corral Service HW Test Logs :** [j3_data_corral_service_hw_test_logs.txt](https://github.com/user-attachments/files/17038148/j3_data_corral_service_hw_test_logs.txt)

### CODE REVIEW

**Comment by kimdo8736** [comment]
Hi, please remove the following 

  "chassisEepromName" : "CHASSIS" ,
  "fruEepromList" : {
    "CHASSIS" : {
      "path" : "/run/devmap/eeproms/COME_EEPROM"
    }
  },

This is weutil.json contents. Please apply the same fixes for tahan and montblanc. Thanks.

**Comment by GoravGargCelestica** [comment]
> Hi, please remove the following
> 
> "chassisEepromName" : "CHASSIS" , "fruEepromList" : { "CHASSIS" : { "path" : "/run/devmap/eeproms/COME_EEPROM" } },
> 
> This is weutil.json contents. Please apply the same fixes for tahan and montblanc. Thanks.

Hi @kimdo8736 

Thankyou for your feedback. 
We have added this EEPROM content intentionally to avoid failures while running the `data_corral_service_hw_test` suite. Without this, test suite has the following error:

```
C++ exception with description "std::runtime_error: Invalid EEPROM name CHASSIS. Valid EEPROM names are: " thrown in the test body.
```

**Complete Log:**  [fail_data_corral_service_hw_test_log.txt](https://github.com/user-attachments/files/17022564/fail_data_corral_service_hw_test_log.txt)

After adding it the test suite is passed successfully : [pass_data_corral_service_hw_test_log.txt](https://github.com/user-attachments/files/17022576/pass_data_corral_service_hw_test_log.txt)

Please let me know your comment.

**Comment by kimdo8736** [comment]
Thanks for the response, with this commit (https://github.com/facebook/fboss/commit/dff361d29b7ae85f966aaf0a7cfa263a9a1d340e)

You can now run without the EEPROM contents. Please let me know how that goes on your end. Thanks.

**Comment by GoravGargCelestica** [comment]
> Thanks for the response, with this commit ([dff361d](https://github.com/facebook/fboss/commit/dff361d29b7ae85f966aaf0a7cfa263a9a1d340e))
> 
> You can now run without the EEPROM contents. Please let me know how that goes on your end. Thanks.

Hi @kimdo8736 , 

Thanks for your feedback.
Yes, with the recent commit ([dff361d](https://github.com/facebook/fboss/commit/dff361d29b7ae85f966aaf0a7cfa263a9a1d340e)) there is no need to have the EEPROM content in the `led_manager.json` , I have updated the changes. Also, attached the latest testing result in the PR description, please help to review again.

Thanks,
Gorav.

**Pull request closed without merging**
